networks:
    web_to_db:
    web_to_ad:


# One or more services can be defined under the top-level key: services.
services:
    # The name postgres is the name of the database service.
    # This arbitrary name becomes the hostname of the container.
    postgres:
        # The image to use to create the container.
        image: postgres:15-alpine
        # The command is passed as arguments to the ENTRYPOINT script. 
        command: "-c shared_buffers=256MB -c max_connections=200"
        # Instructs compose to restart the container if it shuts 
        # down unless the container is intentionally stopped.
        restart: unless-stopped
        healthcheck:
            test: pg_isready -U "$$POSTGRES_USER" -d "$$POSTGRES_PASSWORD" -h postgres
            interval: 3s
            retries: 5
        # The networks attached to the container.
        networks:
            - web_to_db
        # Environment variables used to configure the database. 
        environment:
            - POSTGRES_USER=web_app
            - POSTGRES_PASSWORD=74jrjdSj
            - POSTGRES_DB=postgres

    db_init:
        build: src/webapp
        command: /bin/sh -c "python3 -m webapp.app"
        networks:
            - web_to_db
        environment:
            - DATABASE_HOST=postgres
            - DATABASE_USER=web_app
            - DATABASE_PASS=74jrjdSj
            - DATABASE_NAME=postgres
        depends_on: 
            postgres:
                condition: service_healthy
        restart: "no"

    web_app:
        build: src/webapp
        networks:
            - web_to_db
            - web_to_ad
        ports:
            - "3000:9000"
        environment:
            - DATABASE_HOST=postgres
            - DATABASE_USER=web_app
            - DATABASE_PASS=74jrjdSj
            - DATABASE_NAME=postgres
            - ADSERVE_HOST=adserve
            - ADSERVE_PORT=9000
            - ADSERVE_PATH=/serve
            - SIGNOZ_HOST
        depends_on: 
            postgres:
                condition: service_healthy

    adserve:
        build: src/adserve
        networks:
            - web_to_ad
        environment:
            - SIGNOZ_HOST

